DROP TABLE PERSON;
DROP TABLE BUSINESS CASCADE CONSTRAINTS;
DROP TABLE BUSINESSFORM;
DROP TABLE SCRAP;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_UNO;

CREATE TABLE "MEMBER" (
	"MID"	VARCHAR2(20)		NOT NULL,
	"MPW"	VARCHAR2(20)		NOT NULL,
	"MTYPE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MPW" IS '소문자,대문자,특수문자 포함 8~16자';

COMMENT ON COLUMN "MEMBER"."MTYPE" IS '1 or 2';

CREATE TABLE "PERSON" (
	"MID"	VARCHAR2(20)		NOT NULL,
	"PNAME"	VARCHAR2(50)		NOT NULL,
	"PEMAIL"	VARCHAR2(150)		NOT NULL,
	"PPHONE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "PERSON"."PEMAIL" IS 'id@domain';

COMMENT ON COLUMN "PERSON"."PPHONE" IS '000-0000-0000';

CREATE TABLE "BUSINESS" (
	"MID"	VARCHAR2(20)		NOT NULL,
	"BFORM"	NUMBER		NOT NULL,
	"BRNO"	VARCHAR2(20)		NOT NULL,
	"BIZNAME"	VARCHAR2(50)		NOT NULL,
	"BADDRESS"	VARCHAR2(300)		NOT NULL,
	"BNAME"	VARCHAR2(50)		NOT NULL,
	"BTEL"	VARCHAR2(20)		NOT NULL,
	"BEMAIL"	VARCHAR2(150)		NOT NULL,
	"BIND"	VARCHAR2(100)		NULL,
	"BEMP"	NUMBER		NULL,
	"BESTD"	DATE		NULL,
	"BCAP"	VARCHAR2(20)		NULL,
	"BSALES"	VARCHAR2(20)		NULL,
	"BREP_NAME"	VARCHAR2(50)		NOT NULL,
	"BGRAD_SALARY"	VARCHAR2(20)		NULL,
	"BIND_DETAIL"	VARCHAR2(100)		NULL,
	"BMINS"	VARCHAR2(100)		NULL,
	"BHPAGE"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "BUSINESS"."MID" IS 'ID';

COMMENT ON COLUMN "BUSINESS"."BRNO" IS '000-00-00000';

COMMENT ON COLUMN "BUSINESS"."BTEL" IS '000-0000-0000';

COMMENT ON COLUMN "BUSINESS"."BEMAIL" IS 'id@domain';

CREATE TABLE "BUSINESSFORM" (
	"BFORM"	NUMBER		NOT NULL,
	"BFORM_NAME"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "SCRAP" (
	"JID"	NUMBER		NOT NULL,
	"MID"	VARCHAR2(20)		NOT NULL,
	"RECRUIT_FIELD"	VARCHAR2(20)		NULL,
	"COMPANY_NAME"	VARCHAR2(255)		NULL,
	"BUSINO"	VARCHAR(20)		NULL,
	"USER_EDUCATION"	VARCHAR(50)		NULL,
	"SALARY"	VARCHAR(50)		NULL,
	"MIN_SALARY"	VARCHAR(50)		NULL,
	"MAX_SALARY"	VARCHAR(50)		NULL,
	"REGIST_DATE"	VARCHAR(20)		NULL,
	"CLOSE_DATE"	VARCHAR(20)		NULL,
	"RE_TITLE"	VARCHAR(255)		NULL,
	"CAREER"	VARCHAR(50)		NULL,
	"WORK_TYPE"	VARCHAR(50)		NULL,
	"EMP_TYPE_CODE"	VARCHAR(20)		NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

ALTER TABLE "PERSON" ADD CONSTRAINT "PK_PERSON" PRIMARY KEY (
	"MID"
);

ALTER TABLE "BUSINESS" ADD CONSTRAINT "PK_BUSINESS" PRIMARY KEY (
	"MID"
);

ALTER TABLE "BUSINESSFORM" ADD CONSTRAINT "PK_BUSINESSFORM" PRIMARY KEY (
	"BFORM"
);

ALTER TABLE "PERSON" ADD CONSTRAINT "FK_MEMBER_TO_PERSON_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "BUSINESS" ADD CONSTRAINT "FK_MEMBER_TO_BUSINESS_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "BUSINESS" ADD CONSTRAINT "FK_BUSINESSFORM_TO_BUSINESS_1" FOREIGN KEY (
	"BFORM"
)
REFERENCES "BUSINESSFORM" (
	"BFORM"
);
ALTER TABLE "SCRAP" ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY (
	"JID",
	"MID"
);

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_SCRAP_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);
CREATE SEQUENCE SEQ_UNO;