-- 대분류
INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('0','경영·사무·금융·보험직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('1','연구직 및 공학 기술직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('2','교육·법률·사회복지·경찰·소방직 및 군인');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('3','보건·의료직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('4','예술·디자인·방송·스포츠직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('5','미용·여행·숙박·음식·경비·청소직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('6','영업·판매·운전·운송직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('7','건설·채굴직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('8','설치·정비·생산직');

INSERT INTO "RFField" (JOBSCD, JOBSCAT) VALUES ('9','농림어업직');

--중분류


INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('01', '관리직(임원·부서장)');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('02', '경영·행정·사무직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('03', '금융·보험직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('11', '인문·사회과학 연구직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('12', '자연·생명과학 연구직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('13', '정보통신 연구개발직 및 공학기술직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('14', '건설·채굴 연구개발직 및 공학기술직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('15', '제조 연구개발직 및 공학기술직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('21', '교육직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('22', '법률직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('23', '사회복지·종교직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('24', '경찰·소방·교도직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('25', '군인');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('30', '보건·의료직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('41', '예술·디자인·방송직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('42', '스포츠·레크리에이션직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('51', '미용·예식 서비스직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('52', '여행·숙박·오락 서비스직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('53', '여행·숙박·오락 서비스직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('54', '경호·경비직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('55', '돌봄 서비스직(간병·육아)');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('56', '청소 및 기타 개인서비스직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('61', '영업·판매직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('62', '운전·운송직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('70', '건설·채굴직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('81', '기계 설치·정비·생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('82', '금속·재료 설치·정비·생산직(판금·단조·주조·용접·도장 등)');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('83', '전기·전자 설치·정비·생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('84', '정보통신 설치·정비직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('85', '화학·환경 설치·정비·생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('86', '섬유·의복 생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('87', '식품 가공·생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('88', '인쇄·목재·공예 및 기타 설치·정비·생산직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('89', '제조 단순직');

INSERT INTO "RSField" (JOBSMCD, JOBSMCAT) 
VALUES ('90', '농림어업직');

--소분류

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('011', '의회의원·고위공무원 및 기업 고위임원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('012', '행정·경영·금융·보험 관리자　');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('013', '전문서비스 관리자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('014', '미용·여행·숙박·음식·경비·청소 관리자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('015', '영업·판매·운송 관리자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('016', '건설·채굴·제조·생산 관리자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('021', '정부·공공행정 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('022', '경영·인사 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('023', '회계·세무·감정 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('024', '광고·조사·상품기획·행사기획 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('025', '정부·공공 행정 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('026', '경영지원 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('027', '회계·경리 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('028', '무역·운송·생산·품질 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('029', '안내·고객상담·통계·비서·사무보조 및 기타 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('031', '금융·보험 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('032', '금융·보험 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('033', '금융·보험 영업원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('110', '인문·사회과학 연구원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('121', '자연과학 연구원 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('122', '생명과학 연구원 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('131', '컴퓨터하드웨어·통신공학 기술자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('132', '컴퓨터시스템 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('133', '소프트웨어 개발자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('134', '데이터·네트워크 및 시스템 운영 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('135', '정보보안 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('136', '통신·방송송출 장비 기사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('140', '건축·토목공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('151', '기계·로봇공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('152', '금속·재료공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('153', '전기·전자공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('154', '화학공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('155', '에너지·환경공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('156', '섬유공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('157', '식품공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('158', '소방·방재·산업안전·비파괴 기술자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('159', '제도사 및 기타 인쇄·목재 등 공학 기술자 및 시험원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('211', '대학 교수 및 강사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('212', '학교 교사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('213', '유치원 교사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('214', '문리·기술·예능 강사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('215', '장학관 및 기타 교육 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('221', '법률 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('222', '법률 사무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('231', '사회복지사 및 상담사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('232', '보육교사 및 기타 사회복지 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('233', '성직자 및 기타 종교 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('240', '경찰관, 소방관 및 교도관');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('250', '군인');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('301', '의사, 한의사 및 치과의사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('302', '수의사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('303', '약사 및 한약사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('304', '간호사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('305', '영양사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('306', '의료기사·치료사·재활사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('307', '보건·의료 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('411', '작가·통번역가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('412', '기자 및 언론 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('413', '학예사·사서·기록물관리사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('414', '창작·공연 전문가(작가, 연극 제외)');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('415', '디자이너');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('416', '연극·영화·방송 전문가');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('417', '문화·예술 기획자 및 매니저');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('420', '스포츠·레크리에이션 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('511', '미용 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('512', '결혼·장례 등 예식 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('521', '여행 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('522', '항공기·선박·열차 객실승무원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('523', '숙박시설 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('524', '오락시설 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('531', '주방장 및 조리사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('532', '식당 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('541', '경호·보안 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('542', '경비원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('550', '돌봄 서비스 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('561', '청소·방역 및 가사 서비스원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('562', '검침·주차관리 및 기타 서비스 단순 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('611', '부동산 컨설턴트 및 중개인');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('612', '영업원 및 상품중개인');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('613', '텔레마케터');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('614', '소규모 상점 경영 및 일선 관리 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('615', '판매 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('616', '매장 계산원 및 매표원　');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('617', '판촉 및 기타 판매 단순 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('621', '항공기·선박·철도 조종사 및 관제사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('622', '자동차 운전원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('623', '물품이동장비 조작원(크레인·호이스트·지게차)');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('624', '택배원 및 기타 운송 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('701', '건설구조 기능원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('702', '건축마감 기능원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('703', '배관공');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('704', '건설·채굴 기계 운전원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('705', '기타 건설 기능원(채굴포함)');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('706', '건설·채굴 단순 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('811', '기계장비 설치·정비원(운송장비 제외)');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('812', '운송장비 정비원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('813', '금형원 및 공작기계 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('814', '냉·난방 설비 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('815', '자동조립라인·산업용로봇 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('816', '기계 조립원(운송장비 제외)');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('817', '운송장비 조립원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('821', '금속관련 기계·설비 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('822', '판금원 및 제관원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('823', '단조원 및 주조원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('824', '용접원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('825', '도장원 및 도금원　');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('826', '비금속제품 생산기계 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('831', '전기공');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('832', '전기·전자 기기 설치·수리원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('833', '발전·배전 장치 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('834', '전기·전자 설비 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('835', '전기·전자 부품·제품 생산기계 조작원　');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('836', '전기·전자 부품·제품 조립원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('841', '정보통신기기 설치·수리원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('842', '방송·통신장비 설치·정비원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('851', '석유·화학물 가공장치 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('852', '고무·플라스틱 및 화학제품 생산기계 조작원 및 조립원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('853', '환경관련 장치 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('861', '섬유 제조·가공 기계 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('862', '패턴사, 재단사 및 재봉사');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('863', '의복 제조원 및 수선원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('864', '제화원, 기타 섬유·의복 기계 조작원 및 조립원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('871', '제과·제빵원 및 떡제조원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('872', '식품 가공 기능원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('873', '식품 가공 기계 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('881', '인쇄기계·사진현상기 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('882', '목재·펄프·종이 생산기계 조작원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('883', '가구·목제품 제조·수리원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('884', '공예원 및 귀금속세공원');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('885', '악기·간판 및 기타 제조 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('890', '제조 단순 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('901', '작물재배 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('902', '낙농·사육 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('903', '임업 종사자　');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('904', '어업 종사자');

INSERT INTO "RTField" (JOBSSCD, JOBSSCAT) 
VALUES ('905', '농림어업 단순 종사자');

--세분류

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('011100', '의회의원·고위공무원 및 공공단체임원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('011200', '기업 고위임원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('012100', '정부행정 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('012200', '경영지원 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('012300', '마케팅·광고·홍보 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('012400', '금융·보험 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013100', '연구 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013200', '교육 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013300', '법률·경찰·소방·교도 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013400', '보건·의료 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013500', '사회복지 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013600', '예술·디자인·방송 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013700', '정보통신 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('013900', '부동산·조사·인력알선 및 기타 전문서비스 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('014100', '미용·여행∙숙박·스포츠 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('014200', '음식서비스 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('014300', '경비·청소 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('015100', '영업·판매 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('015200', '운송 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('015900', '기타 판매 및 고객서비스 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('016100', '건설·채굴 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('016200', '전기·가스·수도 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('016300', '제조·생산 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('016900', '기타 건설·전기 및 제조 관리자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('021000', '정부·공공행정 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('022100', '경영·진단 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('022200', '인사·노무 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('023100', '회계사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('023200', '세무사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('023300', '관세사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('023400', '감정 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('024100', '광고·홍보 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('024200', '조사 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('024300', '상품 기획자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('024400', '행사 기획자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('025100', '조세행정 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('025200', '관세행정 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('025300', '병무행정 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('025400', '국가·지방행정 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('025500', '공공행정 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('026100', '기획·마케팅 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('026200', '인사·교육·훈련 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('026300', '총무 사무원 및 대학 행정조교');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('026400', '감사 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('027100', '회계 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('027200', '경리 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('028100', '무역 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('028200', '운송 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('028300', '자재·구매·물류 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('028400', '생산·품질 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029100', '안내·접수원 및 전화교환원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029200', '고객 상담원 및 모니터 요원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029300', '통계 사무원 ');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029400', '비서');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029500', '전산자료 입력원 및 사무 보조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('029900', '기타 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031100', '투자·신용 분석가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031200', '자산 운용가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031300', '보험·금융상품 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031400', '증권·외환 딜러');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031500', '손해사정사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('031900', '기타 금융·보험 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032100', '은행 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032200', '증권 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032300', '보험 심사원 및 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032400', '출납창구 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032500', '수금원 및 신용 추심원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('032900', '기타 금융 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('033100', '대출 및 신용카드 모집인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('033200', '보험 모집인 및 투자 권유 대행인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('110100', '인문과학 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('110200', '사회과학 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('121100', '자연과학 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('121200', '자연과학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('122100', '생명과학 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('122200', '생명과학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('122300', '농림어업 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('131100', '컴퓨터 하드웨어 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('131200', '통신공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('132000', '컴퓨터시스템 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('133100', '시스템 소프트웨어 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('133200', '응용 소프트웨어 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('133300', '웹 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('133900', '기타 컴퓨터 전문가 및 소프트웨어 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('134100', '데이터 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('134200', '네트워크 시스템 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('134300', '정보시스템 운영자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('134400', '웹 운영자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('134900', '기타 데이터 및 네트워크 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('135000', '정보보안 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('136000', '통신·방송송출 장비 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140100', '건축가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140200', '건축공학 기술자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140300', '토목공학 기술자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140400', '조경 기술자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140500', '도시·교통 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140600', '측량·지리정보 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('140700', '건설자재 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('151100', '기계공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('151200', '로봇공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('151300', '기계·로봇공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('152100', '금속·재료공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('152200', '금속·재료공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('153100', '전기공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('153200', '전자공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('153300', '전기·전자공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('154100', '화학공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('154200', '화학공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('155100', '가스·에너지공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('155200', '가스·에너지공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('155300', '환경공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('155400', '환경공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('155500', '보건위생·환경 검사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('156100', '섬유공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('156200', '섬유공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('157100', '식품공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('157200', '식품공학 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('158100', '방재 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('158200', '소방공학 기술자 및 연구원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('158300', '소방공학 시험원 ');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('158400', '산업 안전원 및 위험 관리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('158500', '비파괴 검사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('159100', '제도사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('159900', '기타 인쇄·목재 등 공학 기술자 및 시험원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('211100', '대학 교수');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('211200', '대학 시간강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('212100', '중·고등학교 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('212200', '초등학교 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('212300', '특수교육 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('212900', '기타 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('213000', '유치원 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214100', '문리·어학 강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214200', '컴퓨터 강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214300', '기술·기능계 강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214400', '예능 강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214500', '학습지·교육교구 방문강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('214900', '기타 문리·기술 및 예능 강사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('215100', '장학관·연구관 및 교육 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('215200', '대학 교육 조교(연구 조교(RA) 포함)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('215300', '교사보조 및 보육보조 서비스 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('221100', '판사 및 검사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('221200', '변호사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('221300', '법무사 및 집행관');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('221400', '변리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('221900', '기타 법률 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('222000', '법률 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('231100', '사회복지사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('231200', '상담 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('231300', '청소년 지도사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('231400', '직업상담사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('231500', '시민단체 활동가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('232100', '보육교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('232900', '기타 사회복지 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('233100', '성직자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('233900', '기타 종교 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('240100', '경찰관 및 수사관');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('240200', '소방관');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('240300', '교도관 및 소년원학교 교사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('250100', '영관급 이상 장교');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('250200', '위관급 장교 ');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('250300', '부사관');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('250900', '기타 군인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('301100', '전문 의사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('301200', '일반 의사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('301300', '한의사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('301400', '치과 의사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('302000', '수의사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('303000', '약사 및 한약사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('304000', '간호사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('305000', '영양사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306100', '임상병리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306200', '방사선사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306300', '치과기공사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306400', '치과위생사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306500', '물리 및 작업 치료사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306600', '임상심리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306700', '재활공학 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('306900', '기타 치료·재활사 및 의료기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307100', '응급구조사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307200', '위생사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307300', '안경사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307400', '의무기록사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307500', '간호조무사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307600', '안마사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('307900', '기타 보건·의료 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('411100', '작가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('411200', '번역가 및 통역가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('411300', '출판물 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('412000', '기자 및 언론 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('413100', '학예사 및 문화재 보존원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('413200', '사서 및 기록물 관리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414100', '화가 및 조각가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414200', '사진작가 및 사진사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414300', '만화가 및 만화영화 작가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414400', '국악인 및 전통 예능인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414500', '지휘자, 작곡가 및 연주가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414600', '가수 및 성악가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414700', '무용가 및 안무가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('414900', '기타 시각 및 공연 예술가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('415100', '제품 디자이너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('415200', '패션 디자이너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('415300', '실내장식 디자이너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('415400', '시각 디자이너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('415500', '미디어 콘텐츠 디자이너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416100', '감독 및 기술감독');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416200', '배우 및 모델');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416300', '아나운서 및 리포터');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416400', '촬영 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416500', '음향·녹음 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416600', '영상·녹화·편집 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416700', '조명·영사 기사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('416900', '기타 연극·영화·방송 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('417100', '공연·영화 및 음반 기획자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('417200', '연예인매니저 및 스포츠매니저');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('420100', '스포츠 감독 및 코치');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('420200', '직업 운동선수');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('420300', '경기 심판 및 경기 기록원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('420400', '스포츠강사, 레크리에이션강사 및 기타 관련 전문가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('420900', '기타 스포츠 및 여가서비스 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511100', '이용사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511200', '미용사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511300', '피부 및 체형 관리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511400', '메이크업 아티스트 및 분장사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511500', '반려동물 미용 및 관리 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('511900', '기타 미용 서비스원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('512100', '결혼상담원 및 웨딩플래너');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('512200', '혼례 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('512300', '장례 지도사 및 장례 상담원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('512400', '점술가 및 민속신앙 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('512900', '기타 개인 생활 서비스원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('521100', '여행상품 개발자');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('521200', '여행 사무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('521300', '여행 안내원 및 해설사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('522100', '항공기 객실승무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('522200', '선박·열차 객실승무원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('523000', '숙박시설 서비스원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('524000', '오락시설 서비스원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531100', '주방장 및 요리 연구가');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531200', '한식 조리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531300', '중식 조리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531400', '양식 조리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531500', '일식 조리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531600', '바텐더');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531700', '음료 조리사 ');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('531900', '기타 조리사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('532100', '패스트푸드 준비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('532200', '접객원(홀서빙원)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('532300', '주방 보조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('532400', '음식 배달원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('532900', '기타 음식 서비스 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('541100', '경호원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('541200', '청원경찰');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('541300', '시설·특수 경비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('541900', '기타 경호·보안 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('542000', '경비원(건물 관리원)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('550100', '요양 보호사 및 간병인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('550200', '육아 도우미');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561100', '청소원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561200', '환경미화원 및 재활용품 수거원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561300', '배관 세정원 및 방역원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561400', '구두 미화원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561500', '세탁원(다림질원)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('561600', '가사 도우미');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('562100', '계기 검침원 및 가스 점검원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('562200', '자동판매기 관리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('562300', '주차 관리·안내원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('562400', '검표원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('562900', '기타 서비스 단순 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('611000', '부동산 컨설턴트 및 중개인');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612100', '기술 영업원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612200', '해외 영업원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612300', '자동차 영업원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612400', '제품·광고 영업원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612500', '상품 중개인 및 경매사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('612900', '기타 기술 영업·중개 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('613000', '텔레마케터');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('614000', '소규모 상점 경영 및 일선 관리 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615100', '상점 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615200', '통신 기기·서비스 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615300', '온라인 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615400', '상품 대여원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615500', '노점 및 이동 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615600', '방문 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('615700', '주유원(가스충전원)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('616100', '매장 계산원 및 요금 정산원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('616200', '매표원 및 복권 판매원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('617100', '홍보 도우미 및 판촉원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('617900', '기타 판매 단순 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('621100', '항공기 조종사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('621200', '선장, 항해사 및 도선사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('621300', '철도·전동차 기관사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('621400', '관제사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('621900', '기타 철도운송 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('622100', '택시 운전원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('622200', '버스 운전원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('622300', '화물차·특수차 운전원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('622900', '기타 자동차 운전원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('623000', '물품이동장비 조작원(크레인·호이스트·지게차)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('624100', '택배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('624200', '우편물 집배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('624300', '선박승무원 및 관련 종사원(선박객실 승무원 제외)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('624400', '하역·적재 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('624900', '기타 배달원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701100', '강구조물 가공원 및 건립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701200', '경량철골공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701300', '철근공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701400', '콘크리트공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701500', '건축 석공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701600', '건축 목공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701700', '조적공 및 석재부설원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('701900', '기타 건설 구조 기능원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702100', '미장공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702200', '방수공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702300', '단열공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702400', '바닥재 시공원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702500', '도배공 및 유리 부착원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702600', '건축 도장공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702700', '새시 조립·설치원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('702900', '기타 건축 마감 기능원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('703100', '건설 배관공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('703200', '공업 배관공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('703900', '기타 배관공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('704000', '건설·채굴 기계 운전원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('705100', '광원, 채석원 및 석재 절단원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('705200', '철로 설치·보수원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('705900', '기타 채굴·토목 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('706000', '건설·채굴 단순 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811100', '공업기계 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811200', '승강기 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811300', '물품이동장비 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811400', '냉동·냉장·공조기 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811500', '보일러 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811600', '건설·광업 기계 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('811900', '농업용 및 기타 기계장비 설치·정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('812100', '항공기 정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('812200', '선박 정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('812300', '철도기관차·전동차 정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('812400', '자동차 정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('812900', '기타 운송장비 정비원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('813100', '금형원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('813200', '금속 공작기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('814000', '냉·난방 설비 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('815000', '자동조립라인·산업용로봇 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('816100', '일반기계 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('816200', '금속기계부품 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('817100', '자동차 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('817200', '자동차 부분품 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('817300', '운송장비 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('821100', '금속가공 제어장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('821200', '금속가공 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('822100', '판금원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('822200', '판금기조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('822300', '제관원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('822400', '제관기조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('823100', '단조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('823200', '단조기조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('823300', '주조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('823400', '주조기조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('824100', '용접원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('824200', '용접기조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('825100', '도장원(도장기조작원)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('825200', '도금·금속분무기 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('826100', '유리·유리제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('826200', '점토제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('826300', '시멘트·광물제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('826400', '광석·석제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('826900', '기타 비금속제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('831100', '산업 전기공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('831200', '내선 전기공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('831300', '외선 전기공');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('832100', '사무용 전자기기 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('832200', '가전제품 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('832900', '기타 전기·전자 기기 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('833000', '발전·배전 장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('834000', '전기·전자 설비 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('835100', '전기 부품·제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('835200', '전자 부품·제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('836000', '전기·전자 부품·제품 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('841100', '컴퓨터 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('841200', '이동전화기 수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('841900', '기타 정보통신기기 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('842100', '방송장비 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('842200', '통신장비 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('842300', '방송·통신·인터넷 케이블 설치·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('851100', '석유·천연가스 제조 제어장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('851200', '화학물 가공장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('851900', '기타 석유·화학물 가공장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('852100', '타이어·고무제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('852200', '플라스틱제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('852300', '화학제품 생산기계 조작원(고무·플라스틱 제외)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('852400', '고무·플라스틱 제품 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('853100', '상·하수도 처리장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('853200', '재활용 처리장치·소각로 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('861100', '섬유 제조기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('861200', '직조기·편직기 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('861300', '표백·염색기 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('862100', '패턴사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('862200', '재단사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('862300', '재봉사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('862900', '기타 섬유·가죽 기능원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('863100', '한복 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('863200', '양장·양복 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('863300', '모피·가죽의복 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('863400', '의복·가죽·모피 수선원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('863900', '기타 의복 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('864100', '제화원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('864200', '신발 제조기계 조작원 및 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('864300', '세탁 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('864900', '기타 직물·신발 기계 조작원 및 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('871100', '제과·제빵원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('871200', '떡 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('872100', '정육원 및 도축원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('872200', '김치·밑반찬 제조 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('872300', '식품·담배 등급원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('872900', '기타 식품 가공 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873100', '육류·어패류·낙농품 가공기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873200', '제분·도정 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873300', '곡물 가공제품 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873400', '과실·채소 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873500', '음료 제조기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('873900', '기타 식품 가공 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('881100', '인쇄기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('881200', '사진 인화·현상기 조작원(사진수정 포함)');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('882100', '목재 가공기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('882200', '펄프·종이 제조장치 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('882300', '종이제품 생산기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('882900', '기타 목재·종이 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('883100', '가구 제조·수리원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('883200', '가구 조립원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('883300', '목제품 제조원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('884100', '공예원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('884200', '귀금속·보석 세공원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('885100', '악기 제조원 및 조율사');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('885200', '간판 제작·설치원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('885300', '유리기능, 복사, 수제 제본 등 기타 기능 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('885900', '주입·포장·상표부착기 및 기타 기계 조작원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('890000', '제조 단순 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('901100', '곡식작물 재배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('901200', '채소·특용작물 재배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('901300', '과수작물 재배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('901400', '원예작물 재배원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('901500', '조경원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('902100', '낙농 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('902200', '가축 사육 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('902900', '기타 사육 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('903100', '조림∙산림경영인 및 벌목원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('903900', '임산물 채취 및 기타 임업 종사원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('904100', '양식원');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('904200', '어부 및 해녀');

INSERT INTO RFIELD (RECRUIT_FIELD, FIELD_TITLE) 
VALUES ('905000', '농림어업 단순 종사원');

COMMIT;